# Generated by Django 2.1.2 on 2018-10-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.TextField(default='No Information', max_length=1000)),
                ('option1', models.TextField(default='option 1', max_length=100)),
                ('dfficulty', models.IntegerField(default=1)),
            ],
        ),
    ]
