# Generated by Django 2.1.2 on 2018-10-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionapis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.TextField(max_length=100),
        ),
    ]
