# Generated by Django 2.1.2 on 2018-10-11 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionapis', '0002_auto_20181011_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='dfficulty',
            new_name='difficulty',
        ),
    ]
